# Generated by Django 2.2.4 on 2019-08-03 14:48

import django.db.models.deletion
from django.db import migrations, models

import apps.poker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokerRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('token', models.CharField(default=apps.poker.models.generate_room_token, max_length=127, unique=True, verbose_name='Token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_entry', models.DateTimeField(auto_now=True, verbose_name='Last entry time')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PokerRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='poker.PokerRoom', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PokerMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='poker.PokerRoom', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ('name',),
                'unique_together': {('name', 'room')},
            },
        ),
        migrations.CreateModel(
            name='PockerMemberVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, null=True, verbose_name='Value')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.PokerMember', verbose_name='Member')),
                ('poker_round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.PokerRound', verbose_name='Poker round')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ('member',),
            },
        ),
    ]
