# Generated by Django 2.2.4 on 2019-08-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerroom',
            name='use_time',
            field=models.BooleanField(default=True, verbose_name='Use time'),
        ),
        migrations.AlterField(
            model_name='pokermembervote',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='poker.PokerMember', verbose_name='Member'),
        ),
    ]
