# Generated by Django 2.2.4 on 2019-08-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_auto_20190811_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerMemberRecentRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255, null=True, verbose_name='Session')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recent_members', to='poker.PokerRoom', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Recent room',
                'verbose_name_plural': 'Recent rooms',
                'ordering': ('room__name',),
                'unique_together': {('room', 'session')},
            },
        ),
    ]
