# Generated by Django 2.2.4 on 2020-01-14 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def remove_all_members(apps, schema_editor):
    PokerMember = apps.get_model('poker', 'PokerMember')
    PokerMember.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker', '0003_pokermemberrecentroom'),
    ]

    operations = [
        migrations.RunPython(
            remove_all_members,
            migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name='pokermember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='pokermember',
            unique_together={('room', 'user')},
        ),
        migrations.DeleteModel(
            name='PokerMemberRecentRoom',
        ),
        migrations.RemoveField(
            model_name='pokermember',
            name='session',
        ),
    ]
